# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wzy/miniz

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wzy/miniz

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wzy/miniz/CMakeFiles /home/wzy/miniz/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wzy/miniz/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minilzo_test

# Build rule for target.
minilzo_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minilzo_test
.PHONY : minilzo_test

# fast build rule for target.
minilzo_test/fast:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/build
.PHONY : minilzo_test/fast

examples/example1.o: examples/example1.c.o

.PHONY : examples/example1.o

# target to build an object file
examples/example1.c.o:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/examples/example1.c.o
.PHONY : examples/example1.c.o

examples/example1.i: examples/example1.c.i

.PHONY : examples/example1.i

# target to preprocess a source file
examples/example1.c.i:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/examples/example1.c.i
.PHONY : examples/example1.c.i

examples/example1.s: examples/example1.c.s

.PHONY : examples/example1.s

# target to generate assembly for a file
examples/example1.c.s:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/examples/example1.c.s
.PHONY : examples/example1.c.s

miniz.o: miniz.c.o

.PHONY : miniz.o

# target to build an object file
miniz.c.o:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz.c.o
.PHONY : miniz.c.o

miniz.i: miniz.c.i

.PHONY : miniz.i

# target to preprocess a source file
miniz.c.i:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz.c.i
.PHONY : miniz.c.i

miniz.s: miniz.c.s

.PHONY : miniz.s

# target to generate assembly for a file
miniz.c.s:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz.c.s
.PHONY : miniz.c.s

miniz_tdef.o: miniz_tdef.c.o

.PHONY : miniz_tdef.o

# target to build an object file
miniz_tdef.c.o:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_tdef.c.o
.PHONY : miniz_tdef.c.o

miniz_tdef.i: miniz_tdef.c.i

.PHONY : miniz_tdef.i

# target to preprocess a source file
miniz_tdef.c.i:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_tdef.c.i
.PHONY : miniz_tdef.c.i

miniz_tdef.s: miniz_tdef.c.s

.PHONY : miniz_tdef.s

# target to generate assembly for a file
miniz_tdef.c.s:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_tdef.c.s
.PHONY : miniz_tdef.c.s

miniz_tinfl.o: miniz_tinfl.c.o

.PHONY : miniz_tinfl.o

# target to build an object file
miniz_tinfl.c.o:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_tinfl.c.o
.PHONY : miniz_tinfl.c.o

miniz_tinfl.i: miniz_tinfl.c.i

.PHONY : miniz_tinfl.i

# target to preprocess a source file
miniz_tinfl.c.i:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_tinfl.c.i
.PHONY : miniz_tinfl.c.i

miniz_tinfl.s: miniz_tinfl.c.s

.PHONY : miniz_tinfl.s

# target to generate assembly for a file
miniz_tinfl.c.s:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_tinfl.c.s
.PHONY : miniz_tinfl.c.s

miniz_zip.o: miniz_zip.c.o

.PHONY : miniz_zip.o

# target to build an object file
miniz_zip.c.o:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_zip.c.o
.PHONY : miniz_zip.c.o

miniz_zip.i: miniz_zip.c.i

.PHONY : miniz_zip.i

# target to preprocess a source file
miniz_zip.c.i:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_zip.c.i
.PHONY : miniz_zip.c.i

miniz_zip.s: miniz_zip.c.s

.PHONY : miniz_zip.s

# target to generate assembly for a file
miniz_zip.c.s:
	$(MAKE) -f CMakeFiles/minilzo_test.dir/build.make CMakeFiles/minilzo_test.dir/miniz_zip.c.s
.PHONY : miniz_zip.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... minilzo_test"
	@echo "... edit_cache"
	@echo "... examples/example1.o"
	@echo "... examples/example1.i"
	@echo "... examples/example1.s"
	@echo "... miniz.o"
	@echo "... miniz.i"
	@echo "... miniz.s"
	@echo "... miniz_tdef.o"
	@echo "... miniz_tdef.i"
	@echo "... miniz_tdef.s"
	@echo "... miniz_tinfl.o"
	@echo "... miniz_tinfl.i"
	@echo "... miniz_tinfl.s"
	@echo "... miniz_zip.o"
	@echo "... miniz_zip.i"
	@echo "... miniz_zip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

